"""
BPE tokenizer.

GENERATED by bpe-tokenizer.ipynb — do not edit this file by hand.
Edit the notebook cells and re-run the "generate bpe.py" cell instead.
"""
import collections
import pickle
import re
import string

from tqdm.auto import tqdm

SEGMENT_RE = re.compile(r'\S+|\s+')
DEFAULT_TOKENIZER_PATH = 'checkpoints/bpe_tokenizer.pkl'

END_OF_TEXT = '<|endoftext|>'

def word_frequencies(text):
    """Split text into segments and count how often each one occurs."""
    freq = {}
    for segment in SEGMENT_RE.findall(text):
        freq[segment] = freq.get(segment, 0) + 1
    return freq


def bpe_train(text, vocab_size=512, special_tokens=(), chars=None, verbose=True,
              show_first=10, every=200):
    """
    Train a BPE tokenizer on text.

    The vocabulary is laid out in three blocks, and everything downstream relies on it:

        [ characters ][ merges, in the order learned ][ special tokens ]

    so the merge of rank i always lives at id len(chars) + i, and the special tokens
    always occupy the tail. `vocab_layout` below recovers the block boundaries.

    special_tokens are reserved ids at the END of the vocabulary. They take no part
    in merging - they are markers the model must never see split apart - so they are
    appended after the merge loop and simply reduce the merge budget.

    chars overrides the character inventory, which is otherwise taken from `text`.
    Pass it when learning merges from a sample of a larger corpus: merge frequencies
    converge on a sample, but the *character set* does not, and any character missing
    from the vocabulary makes bpe_encode raise on the full corpus later.

    Returns:
        vocab  - list of token strings; index = token id
        merges - list of (id_a, id_b) merge rules in training order

    len(vocab) == vocab_size UNLESS the corpus runs out of pairs to merge, which can
    happen on a tiny corpus; the function says so rather than failing quietly.
    """
    # The vocabulary starts as every character in the corpus, sorted for reproducibility.
    if chars is None:
        chars = sorted(set(text))
    else:
        chars = sorted(set(chars))
        missing = sorted(set(text) - set(chars))
        if missing:
            raise ValueError(
                f"`chars` omits {len(missing)} character(s) present in the training "
                f"text: {''.join(missing[:20])!r}")
    vocab = chars[:]
    encoder = {c: i for i, c in enumerate(chars)}
    merges = []

    # Each unique segment is held as a tuple of ids, and carries its frequency.
    word_freq = word_frequencies(text)
    word_ids = {w: tuple(encoder[c] for c in w) for w in word_freq}

    # Reserve the tail of the vocabulary for the special tokens.
    merge_target = vocab_size - len(special_tokens)
    n_merges = merge_target - len(chars)
    if n_merges < 0:
        raise ValueError(
            f"vocab_size={vocab_size} is too small: the character inventory has "
            f"{len(chars)} entries and {len(special_tokens)} special token(s) are "
            f"reserved, so at least {len(chars) + len(special_tokens)} ids are needed "
            f"before any merging.")

    exhausted = False
    while len(vocab) < merge_target:
        # Count adjacent pairs across unique segments, weighted by frequency.
        counts = {}
        for w, freq in word_freq.items():
            ids = word_ids[w]
            for a, b in zip(ids, ids[1:]):
                counts[(a, b)] = counts.get((a, b), 0) + freq
        if not counts:
            exhausted = True
            break   # every segment is a single token; nothing left to merge

        # The most frequent pair becomes the next token.
        best = max(counts, key=counts.get)
        new_tok = vocab[best[0]] + vocab[best[1]]
        new_id = len(vocab)
        vocab.append(new_tok)
        encoder[new_tok] = new_id
        merges.append(best)

        # Rewrite every segment, replacing that pair with the new id.
        for w in word_freq:
            ids = word_ids[w]
            merged, i = [], 0
            while i < len(ids):
                if i < len(ids) - 1 and (ids[i], ids[i + 1]) == best:
                    merged.append(new_id)
                    i += 2
                else:
                    merged.append(ids[i])
                    i += 1
            word_ids[w] = tuple(merged)

        done = len(vocab) - len(chars)
        if verbose and (done <= show_first or done % every == 0):
            print(f"  merge {done:4d}/{n_merges}: "
                  f"{vocab[best[0]]!r} + {vocab[best[1]]!r} -> {new_tok!r} "
                  f"({counts[best]:,} occurrences)")

    vocab.extend(special_tokens)

    if exhausted and verbose:
        print(f"  stopped after {len(merges)} of {n_merges} merges: the corpus has no "
              f"adjacent pairs left to merge, so every segment is already a single "
              f"token. The vocabulary is {len(vocab)}, not the {vocab_size} requested.")
    if verbose:
        total = sum(len(word_ids[w]) * f for w, f in word_freq.items())
        extra = f" + {len(special_tokens)} special" if special_tokens else ""
        print(f"Done: vocab_size={len(vocab)} ({len(chars)} characters + "
              f"{len(merges)} merges{extra}), training text compressed to {total:,} "
              f"tokens ({len(text)/total:.2f} characters per token)")
    return vocab, merges


def vocab_layout(vocab, merges):
    """
    Recover the [characters][merges][specials] block boundaries of a vocabulary.

    The character block is exactly the leading run of single-character tokens: a
    merge concatenates two tokens so it is never shorter than two characters, and
    special tokens are appended last. Everything after the characters and the
    merges is therefore a special token.

    Returns (n_chars, n_special).
    """
    n_chars = 0
    while n_chars < len(vocab) and len(vocab[n_chars]) == 1:
        n_chars += 1
    n_special = len(vocab) - n_chars - len(merges)
    if n_special < 0:
        raise ValueError(
            f"vocab and merges disagree: {len(vocab)} tokens, {n_chars} characters "
            f"and {len(merges)} merges leaves no room for the merge block.")
    return n_chars, n_special


def _apply_bpe_merges(ids, merge_rules):
    """Apply merge rules, in training order, to one segment."""
    for a, b, new_id in merge_rules:
        merged, i = [], 0
        while i < len(ids):
            if i < len(ids) - 1 and ids[i] == a and ids[i + 1] == b:
                merged.append(new_id)
                i += 2
            else:
                merged.append(ids[i])
                i += 1
        ids = merged
    return tuple(ids)


def bpe_encode(text, vocab, merges, verbose=None):
    """
    Convert text to a list of token ids.

    Special tokens are split out of the text first and each becomes exactly one id.
    They must not reach SEGMENT_RE: a segment is not a token, and without a reserved
    id the separator would be encoded character by character and merged like an
    ordinary word.

    Raises ValueError if text contains a character outside the vocabulary. This
    tokenizer is character-based, so its vocabulary is closed: there is no fallback
    that could represent a character it does not hold. A byte-level BPE has no such
    failure mode, because every byte value is in the vocabulary by construction.
    """
    n_chars, n_special = vocab_layout(vocab, merges)

    # Ids are read off the layout, never looked up by string. A learned merge can
    # coincide with a special token's spelling, and a string lookup would then
    # silently return the special token's id for ordinary text.
    merge_rules = [(a, b, n_chars + i) for i, (a, b) in enumerate(merges)]
    specials = vocab[n_chars + len(merges):]
    special_id = {t: n_chars + len(merges) + i for i, t in enumerate(specials)}

    # Longest first, so <|endoftext|> wins over any special that is a prefix of it.
    if specials:
        pattern = '|'.join(re.escape(t) for t in sorted(specials, key=len, reverse=True))
        chunks = re.split('(' + pattern + ')', text)
        is_special = [False] * len(chunks)
        for i in range(1, len(chunks), 2):     # re.split puts captures at odd indices
            is_special[i] = True
    else:
        chunks, is_special = [text], [False]

    plain = ''.join(c for c, sp in zip(chunks, is_special) if not sp)
    unknown = sorted(set(plain) - set(vocab[:n_chars]))
    if unknown:
        shown = ''.join(unknown[:20])
        raise ValueError(
            f"{len(unknown)} character(s) are not in the tokenizer vocabulary: {shown!r}. "
            f"The vocabulary is closed: it holds only the characters it was built with - "
            f"either they never occurred in the training corpus, or they were too rare "
            f"to be worth a slot and clean_corpus dropped them. A character-based BPE has "
            f"no fallback for anything else. Lower min_count when cleaning, train on a "
            f"corpus that covers this text, or switch to a byte-level BPE."
        )
    char_id = {c: i for i, c in enumerate(vocab[:n_chars])}

    # Identical segments encode identically, so encode each distinct one once.
    chunk_segments = [None if sp else SEGMENT_RE.findall(c)
                      for c, sp in zip(chunks, is_special)]
    unique_segments = list(dict.fromkeys(
        s for segs in chunk_segments if segs is not None for s in segs))
    show_progress = len(unique_segments) > 1000 if verbose is None else verbose

    encoded_cache = {}
    for segment in tqdm(unique_segments, desc="BPE encoding", disable=not show_progress):
        ids = [char_id[c] for c in segment]
        encoded_cache[segment] = _apply_bpe_merges(ids, merge_rules)

    encoded = []
    for chunk, segments in zip(chunks, chunk_segments):
        if segments is None:
            encoded.append(special_id[chunk])       # one id for the whole special token
        else:
            for segment in segments:
                encoded.extend(encoded_cache[segment])
    return encoded


def bpe_decode(ids, vocab):
    """Convert a list of token ids back to text."""
    return ''.join(vocab[i] for i in ids if 0 <= i < len(vocab))


def clean_corpus(documents, min_count=100, always_keep=None, verbose=True):
    """
    Drop documents that use characters too rare to deserve a vocabulary slot.

    A character is kept if it occurs at least min_count times, or if it is in
    always_keep (by default all printable ASCII, so ordinary input never fails).
    Documents containing anything else are removed whole - never edited, so a
    cleaned document is always an original one.

    Returns:
        kept  - the surviving documents
        chars - the character inventory to hand to bpe_train(chars=...)
    """
    if always_keep is None:
        always_keep = set(string.printable)

    counts = collections.Counter()
    for doc in documents:
        counts.update(doc)

    keep = {c for c, k in counts.items() if k >= min_count}
    keep |= set(always_keep) & set(counts)
    rare = set(counts) - keep

    if rare:
        kept = [d for d in documents if not (set(d) & rare)]
    else:
        kept = list(documents)

    if verbose:
        n_before = sum(len(d) for d in documents)
        n_after = sum(len(d) for d in kept)
        dropped = len(documents) - len(kept)
        print(f"characters: {len(counts)} distinct -> {len(keep)} kept, "
              f"{len(rare)} dropped ({sum(counts[c] for c in rare):,} occurrences)")
        print(f"documents:  {len(documents):,} -> {len(kept):,} "
              f"({dropped:,} dropped, {dropped/max(len(documents),1):.4%})")
        print(f"text:       {n_before:,} -> {n_after:,} characters "
              f"({(n_before-n_after)/max(n_before,1):.4%} removed)")
        if rare:
            worst = sorted(rare, key=lambda c: -counts[c])[:15]
            print(f"dropped characters (most frequent first): "
                  f"{''.join(worst)!r}{' …' if len(rare) > 15 else ''}")

    return kept, sorted(keep)


def bpe_save(vocab, merges, path=DEFAULT_TOKENIZER_PATH):
    """Save vocab and merges to a pickle file."""
    with open(path, 'wb') as f:
        pickle.dump({'vocab': vocab, 'merges': merges}, f)
    print(f"Saved tokenizer to {path} (vocab_size={len(vocab)})")


def bpe_load(path=DEFAULT_TOKENIZER_PATH):
    """Load vocab and merges from a pickle file."""
    with open(path, 'rb') as f:
        state = pickle.load(f)
    return state['vocab'], [tuple(m) for m in state['merges']]
