"""
nanochat model: a minimal GPT in pure JAX.

GENERATED by nanochat.ipynb — do not edit this file by hand.
Edit the notebook cells and re-run the "generate nanochat_model.py" cell instead.
"""
import math
import os
import pickle

import jax
import jax.numpy as jnp
import numpy as np

from bpe import bpe_encode, bpe_decode, vocab_layout

DEFAULT_CHECKPOINT_PATH = 'checkpoints/nanochat_checkpoint.pkl'

def rms_norm(g, x, eps=1e-6):
    """
    g : (d,)         learned gain
    x : (..., d)     input tensor
    """
    rms = jnp.sqrt(jnp.mean(x**2, axis=-1, keepdims=True) + eps)
    return g * (x / rms)


def precompute_rope(seq_len: int, head_dim: int, base: float = 10000.0):
    """
    Returns cos, sin arrays of shape (seq_len, head_dim).
    Precomputed once; passed as constants to forward().
    """
    i      = jnp.arange(0, head_dim, 2)          # (head_dim//2,)
    theta  = 1.0 / (base ** (i / head_dim))       # frequencies
    pos    = jnp.arange(seq_len)                  # (seq_len,)
    angles = jnp.outer(pos, theta)                # (seq_len, head_dim//2)
    angles = jnp.concatenate([angles, angles], axis=-1)  # (seq_len, head_dim)
    return jnp.cos(angles), jnp.sin(angles)       # both (seq_len, head_dim)


def rotate_half(x):
    """Rotate the last dimension in pairs: [x1, x2] -> [-x2, x1]."""
    d = x.shape[-1] // 2
    return jnp.concatenate([-x[..., d:], x[..., :d]], axis=-1)


def apply_rope(x, cos, sin):
    """
    x   : (..., T, head_dim)
    cos : (T, head_dim) or broadcastable
    sin : (T, head_dim) or broadcastable
    """
    return x * cos + rotate_half(x) * sin


def qk_norm(x, eps=1e-6):
    """
    Parameter-free RMS normalisation along the head dimension.

    x : (..., head_dim)
    Leaves ||x||_2 = sqrt(head_dim), not 1 — see the discussion above.
    """
    rms = jnp.sqrt(jnp.mean(x**2, axis=-1, keepdims=True) + eps)
    return x / rms


def attention_forward(params_attn, x, cos, sin, mask):
    """
    params_attn : dict with Wq, Wk, Wv, Wo each (d_model, d_model)
    x           : (B, T, d_model)
    cos, sin    : (T, head_dim)
    mask        : (T, T)
    Returns     : (B, T, d_model), attn_weights (B, n_heads, T, T)
    """
    B, T, d = x.shape
    head_dim = cos.shape[-1]   # concrete: inferred from RoPE table shape
    n_heads  = d // head_dim   # concrete: integer division of static dims

    Wq, Wk, Wv, Wo = (params_attn['Wq'], params_attn['Wk'],
                       params_attn['Wv'], params_attn['Wo'])

    # Linear projections
    Q = x @ Wq                    # (B, T, d)
    K = x @ Wk
    V = x @ Wv

    # Reshape to (B, T, n_heads, head_dim)
    def split_heads(t):
        return t.reshape(B, T, n_heads, head_dim).transpose(0, 2, 1, 3)  # (B, H, T, hd)

    Q, K, V = split_heads(Q), split_heads(K), split_heads(V)

    # Apply RoPE (broadcast over batch and head dims)
    cos_ = cos[None, None, :, :]   # (1, 1, T, head_dim)
    sin_ = sin[None, None, :, :]
    Q = apply_rope(Q, cos_, sin_)
    K = apply_rope(K, cos_, sin_)

    # QK Normalisation: RMS per token per head, parameter-free
    Q = qk_norm(Q)
    K = qk_norm(K)

    # Scaled dot-product attention
    scale  = math.sqrt(head_dim)
    scores = (Q @ K.transpose(0, 1, 3, 2)) / scale   # (B, H, T, T)
    scores = scores + mask[None, None, :, :]           # causal mask
    weights = jax.nn.softmax(scores, axis=-1)          # (B, H, T, T)

    # Weighted sum of values
    out = weights @ V                                  # (B, H, T, hd)
    out = out.transpose(0, 2, 1, 3).reshape(B, T, d)  # (B, T, d)
    out = out @ Wo                                     # (B, T, d)
    return out, weights


def causal_mask(seq_len: int):
    """Lower-triangular causal mask: 0 where allowed, -inf where masked."""
    mask = jnp.tril(jnp.ones((seq_len, seq_len)))
    return jnp.where(mask, 0.0, -jnp.inf)   # (T, T)


def mlp_forward(params_mlp, x):
    """
    params_mlp: {'W1': (d, 4d), 'W2': (4d, d)}
    x         : (B, T, d)
    """
    x = x @ params_mlp['W1']              # (B, T, 4d)
    x = jax.nn.relu(x)                    # ReLU
    x = x * x                             # ReLU²
    return x @ params_mlp['W2']           # (B, T, d)


def init_params(key, vocab_size, d_model=128, n_heads=4, n_layers=4, d_ff=None):
    """
    Initialise all NanoChatGPT parameters as a plain nested dict (JAX pytree).

    Returns
    -------
    params : dict
        Nested dict — the sole source of model state.
    config : dict
        Hyperparameters needed by forward().
    """
    if d_ff is None:
        d_ff = 4 * d_model
    head_dim = d_model // n_heads

    def W(key, shape):
        return jax.random.normal(key, shape) * 0.02

    # Split all keys upfront: 6 per layer (Wq, Wk, Wv, Wo, W1, W2) + 2 (tok_emb, head)
    keys = list(jax.random.split(key, 6 * n_layers + 2))

    blocks = []
    for _ in range(n_layers):
        blocks.append({
            'norm1': {'g': jnp.ones(d_model)},
            'attn': {
                'Wq': W(keys.pop(), (d_model, d_model)),
                'Wk': W(keys.pop(), (d_model, d_model)),
                'Wv': W(keys.pop(), (d_model, d_model)),
                'Wo': W(keys.pop(), (d_model, d_model)),
            },
            'norm2': {'g': jnp.ones(d_model)},
            'mlp': {
                'W1': W(keys.pop(), (d_model, d_ff)),
                'W2': W(keys.pop(), (d_ff,  d_model)),
            },
        })

    params = {
        'tok_emb': {'W': W(keys.pop(), (vocab_size, d_model))},
        'blocks':  blocks,
        'norm_f':  {'g': jnp.ones(d_model)},
        'head':    {'W': W(keys.pop(), (vocab_size, d_model))},  # untied LM head
    }

    config = dict(vocab_size=vocab_size, d_model=d_model, n_heads=n_heads,
                  n_layers=n_layers, d_ff=d_ff, head_dim=head_dim)
    return params, config


def count_params(pytree):
    leaves = jax.tree_util.tree_leaves(pytree)
    return sum(x.size for x in leaves if hasattr(x, 'size'))


def forward(params, token_ids, cos, sin, mask):
    """
    Pure-function forward pass — no side effects.
    B: batch size, T: sequence length, 
    d_model: model dimension, head_dim: attention head dimension

    Parameters
    ----------
    params    : pytree dict from init_params
    token_ids : (B, T) int array
    cos, sin  : (T, head_dim) RoPE tables
    mask      : (T, T) causal mask

    Returns
    -------
    logits : (B, T, vocab_size)
    """
    # Token embedding
    x = params['tok_emb']['W'][token_ids]   # (B, T, d_model)

    # Transformer blocks
    for blk in params['blocks']:
        # ── Self-attention with rms pre-norm ──────────────────────────────
        x_normed = rms_norm(blk['norm1']['g'], x)
        attn_out, _ = attention_forward(blk['attn'], x_normed, cos, sin, mask)
        x = x + attn_out

        # ── MLP with pre-norm ─────────────────────────────────────────
        x_normed = rms_norm(blk['norm2']['g'], x)
        x = x + mlp_forward(blk['mlp'], x_normed)

    # Final norm and LM head
    x = rms_norm(params['norm_f']['g'], x)        # (B, T, d_model)
    logits = x @ params['head']['W'].T            # (B, T, vocab_size)
    return logits


def cross_entropy_loss(logits, targets):
    """
    B: batch size, T: token count, V: vocabulary size
    logits : (B*T, V) float32
    targets: (B*T,)  int32
    Returns scalar mean cross-entropy.
    """
    log_probs = jax.nn.log_softmax(logits, axis=-1) # (B*T, V)
    # Gather log-prob of the correct token at each position
    logliks = log_probs[jnp.arange(targets.shape[0]), targets] # (B*T,)
    return -jnp.mean(logliks)


def save_checkpoint(
    params,
    cfg,
    vocab,
    merges,
    path='checkpoints/nanochat_checkpoint.pkl',
    *,
    opt_state=None,
    step=0,
    train_losses=None,
    val_log=None,
    best_val=None,
    best_step=None,
    verbose=False,
):
    """Save params, optimizer state, and training metadata to a pickle file."""
    directory = os.path.dirname(path)
    if directory:                       # '' when path is a bare filename
        os.makedirs(directory, exist_ok=True)
    with open(path, 'wb') as f:
        pickle.dump({
            'params': jax.tree_util.tree_map(np.array, params),
            'opt_state': None if opt_state is None else jax.tree_util.tree_map(np.array, opt_state),
            'cfg': cfg,
            'vocab': vocab,
            'merges': merges,
            'step': step,
            'train_losses': [] if train_losses is None else list(train_losses),
            'val_log': [] if val_log is None else list(val_log),
            'best_val': best_val,
            'best_step': best_step,
        }, f)
    if verbose:
        print(f'Checkpoint saved -> {path}')


def load_checkpoint(path='checkpoints/nanochat_checkpoint.pkl'):
    """
    Load params, optimizer state, and training metadata from a pickle file.

    Returns a **dict** — every notebook in this series unpacks it the same way.
    """
    with open(path, 'rb') as f:
        s = pickle.load(f)
    s['params'] = jax.tree_util.tree_map(jnp.array, s['params'])
    if s.get('opt_state') is not None:
        s['opt_state'] = jax.tree_util.tree_map(jnp.array, s['opt_state'])
    s['merges'] = [tuple(m) for m in s['merges']]
    s.setdefault('step', 0)
    s.setdefault('train_losses', [])
    s.setdefault('val_log', [])
    s.setdefault('best_val', float('inf'))
    s.setdefault('best_step', 0)
    return s


def sample_token(key, logits, temperature=1.0, top_k=0, top_p=1.0):
    """Sample one token id from a logit vector. logits: (V,)"""
    if temperature == 0.0:
        return jnp.argmax(logits)                 # greedy

    logits = logits / temperature

    if top_k > 0:                                 # keep the k largest logits
        kth = jnp.sort(logits)[-top_k]
        logits = jnp.where(logits < kth, -jnp.inf, logits)

    probs = jax.nn.softmax(logits)

    if top_p < 1.0:                               # keep the nucleus
        order = jnp.argsort(-probs)
        cumulative = jnp.cumsum(probs[order])
        # always keep the top token, then every token whose predecessors have
        # not yet accumulated p of the mass
        keep = jnp.concatenate([jnp.array([True]), cumulative[:-1] < top_p])
        mask = jnp.zeros_like(probs).at[order].set(keep.astype(probs.dtype))
        probs = probs * mask
        probs = probs / probs.sum()

    return jax.random.choice(key, probs.shape[0], p=probs)


@jax.jit
def next_token_logits(params, buf, n, cos, sin, mask):
    """Logits for the token after position n-1. `buf` always has shape (seq_len,),
    and cos/sin/mask are passed in rather than rebuilt, so XLA compiles this once."""
    logits = forward(params, buf[None], cos, sin, mask)
    return logits[0, n - 1]


def generate(model, prompt, max_new_tokens=80, temperature=1.0,
             top_k=0, top_p=1.0, key=None, stop_at_eot=True):
    """
    Generate a continuation of `prompt`. Returns the new text only.

    `model` is a checkpoint dict: {'params', 'cfg', 'vocab', 'merges'}.
    """
    params, cfg_ = model['params'], model['cfg']
    vocab_, merges_ = model['vocab'], model['merges']
    if key is None:
        key = jax.random.key(0)

    seq_len = cfg_['seq_len']
    cos, sin = precompute_rope(seq_len, cfg_['head_dim'])   # hoisted out of the loop
    mask = causal_mask(seq_len)
    eot = len(vocab_) - vocab_layout(vocab_, merges_)[1]

    # Keep the last seq_len - 1 prompt tokens, not seq_len: a prompt that exactly
    # fills the buffer would otherwise leave no room to write a single new token,
    # and the loop below would return an empty string rather than an error.
    ids = bpe_encode(prompt, vocab_, merges_)[-(seq_len - 1):]
    n = len(ids)
    buf = jnp.zeros(seq_len, dtype=jnp.int32).at[:n].set(jnp.array(ids))

    new_tokens = []
    for _ in range(max_new_tokens):
        if n >= seq_len:                       # context window is full
            break
        logits = next_token_logits(params, buf, n, cos, sin, mask)
        key, subkey = jax.random.split(key)
        token = int(sample_token(subkey, logits, temperature, top_k, top_p))
        if stop_at_eot and token == eot:       # the model chose to stop
            break
        new_tokens.append(token)
        buf = buf.at[n].set(token)
        n += 1

    return bpe_decode(new_tokens, vocab_)
